### ISSUE TITLE
No overflow detection

### ISSUE THREAD

**Issue by KristofferC** [JuliaComputing/TextParse.jl#79]
Should this be caught? 

```jl
julia> TextParse.tryparsenext_base10(Int32, "433213123232131231232131231132115",1,40)
(Some(-19125805), 34)
```

**Comment by davidanthoff** [comment]
Yes, I think it should! ``Int`` parsing in general needs some love, we don’t do so well on it in terms of perf. 

There is also the question of what to do in this case. My sense is that if a user specified a column type ``Int64``, this should throw an error. If the column type was auto detected, we could either promote automatically to a larger ``Int`` type, or switch the column over to ``String``. The former probably makes more sense? But I’m not sure... The latter would require some more work because promoting to ``String`` is not trivial (we need to reparse that column), but that is something I’ve started working on in any case.
